### ISSUE TITLE
macOS版への対応

### ISSUE THREAD

**Issue by nullplus** [sha5010/vim.xlam#37]
こんにちは。とても気になるアドインです。
regexを使った部分を制限するなどして、macOS版で動かすことはできるでしょうか。

---
macOS版でも使えるかな？と思い、インストールを試みましたが、Dictionaryおよびregex対応の面で機能しないようでした。

Dictionaryは下記ライブラリを試してみましたが、regexは既存の代替品が無く、読み込み時点でエラーになります。
https://github.com/VBA-tools/VBA-Dictionary

**Comment by sha5010** [comment]
興味を持っていただき、ありがとうございます。

ご質問のMac版での動作ですが、残念ながら難しいと考えています。
本アドインでは多くの機能でWindowsAPIを利用しておりますが、MacではWindowsAPIが使えないはずです。(未検証)
中でも`keybd_event`というキー操作をおこなうAPIを多用しており、これが使えないとなると多くの機能を再実装する必要があると考えられます。(`hjkl`の移動系コマンドは矢印キーにマップしているが、これをセル選択に実装しなおす等)

Regex系の利用を避け、Dictionaryを紹介いただいたものに置き換えた上で機能の再実装をすれば、動作させられるかもしれません。
ただMac版のExcel VBAは全然詳しくないので、どこまでできるのかは正直わかりません。

**Comment by nullplus** [comment]
ありがとうございます。
伺った内容から察するにWindowsAPI部分をApppleScriptに置き換える作業になるかもですね...。

**Comment by nullplus** [comment]
OK!
気が向いたときに、調査＆実装してみるかもなので、forkしておきます><!!

Thank you ;)

**Comment by sha5010** [comment]
フォークありがとうございます。
一旦、本Issueはクローズさせていただきます。

---
Mac版の開発に興味がある方へ
以下のリポジトリへご協力いただければと思います。

For those interested in developing a Mac version
Please cooperate with the following forked repository.

https://github.com/nullplus/macvim.xlam
